global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    metrics_path: /metrics
    static_configs:
      - targets: ['127.0.0.1:80', '127.0.0.1:9901', '172.26.9.223:80', '192.168.43.11:80', '192.168.1.103:80']