apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra-deploy
spec:
  selector:
    app: cassandra-pod
  ports:
    - protocol: TCP
      port: 9042
      targetPort: 9042
