apiVersion: v1
kind: Service
metadata:
  name: envoy-service
  labels:
    app: envoy-service
spec:
  selector:
    app: envoy-pod
  type: NodePort
  ports:
    - name: proxy 
      protocol: TCP
      port: 10000
      targetPort: 10000
      nodePort: 30100
    - name: admin
      protocol: TCP
      port: 9901
      targetPort: 9901
      nodePort: 30901