kind: Service
apiVersion: v1
metadata:
  name: grafana-service
  labels:
    app: grafana-service
spec:
  selector:
    app: grafana-pod
  type:  NodePort
  ports:
    - protocol: TCP
      port:  3001
      targetPort:  3000