apiVersion: v1
kind: Service
metadata:
  name: psql-service
  labels:
    app: psql-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    app: psql-pod