apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: broker-service
spec:
  selector:
    app: broker-server
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80 
      # nodePort: 30080
    - name: grpc
      port: 50051
      targetPort: 50051
      # nodePort: 30050