apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  selector:
    app: jaeger-pod
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
    - protocol: UDP
      port: 6831
      targetPort: 6831